---
title: "Final Project"
author: "LeTicia Cancel"
date: "11/30/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Libraries
```{r}
#install.packages("SASxport")
library(dplyr)
library(tidyverse)
library(ggplot2)
```


OSEMN Framework

Obtain

Read CSV file from Github
```{r}
#Master Suicide Rate CSV file
master_sr_file <- "https://raw.githubusercontent.com/ltcancel/Final-Project/master/Global_Suicide_Rate.csv"

master_sr <- read.csv(master_sr_file, sep = ",", header = TRUE)
head(master_sr)

#Happiness data
file2015 <- "https://raw.githubusercontent.com/ltcancel/Final-Project/master/2015.csv"
file2016 <- "https://raw.githubusercontent.com/ltcancel/Final-Project/master/2016.csv"
file2017 <- "https://raw.githubusercontent.com/ltcancel/Final-Project/master/2017.csv"
file2018 <- "https://raw.githubusercontent.com/ltcancel/Final-Project/master/2018.csv"
file2019 <- "https://raw.githubusercontent.com/ltcancel/Final-Project/master/2019.csv"

happy2015 <- read.csv(file2015, sep = ",", header = TRUE)
happy2016 <- read.csv(file2016, sep = ",", header = TRUE)
happy2017 <- read.csv(file2017, sep = ",", header = TRUE)
happy2018 <- read.csv(file2018, sep = ",", header = TRUE)
happy2019 <- read.csv(file2019, sep = ",", header = TRUE)

#head(happy2015)

happy2015 <- add_column(happy2015, year = 2015)
happy2016 <- add_column(happy2016, year = 2016)
happy2017 <- add_column(happy2017, year = 2017)
happy2018 <- add_column(happy2018, year = 2018)
happy2019 <- add_column(happy2019, year = 2019)

#head(happy2015)
#head(happy2016)

#master.happy <- rbind(happy2015,happy2016)

#Region tibble for later use
region <- happy2015[,1:2] %>%
  group_by(Country) %>%
  group_by(Region)

region

#select subset  
happy2019 <- select(happy2019,Country.or.region,Overall.rank,Score,Healthy.life.expectancy,Generosity,year)
head(happy2019)

happy2018 <- select(happy2018,Country.or.region,Overall.rank,Score,Healthy.life.expectancy,Generosity,year)
happy2017 <- select(happy2017,Country,Happiness.Rank,Happiness.Score,Health..Life.Expectancy.,Generosity,year)
happy2016 <- select(happy2016,Country,Happiness.Rank,Happiness.Score,Health..Life.Expectancy.,Generosity,year)
happy2015 <- select(happy2015,Country,Happiness.Rank,Happiness.Score,Health..Life.Expectancy.,Generosity,year)

master.happy <- rbind(happy2015,happy2016,happy2017)
master.happy
```


Scrub with joins
```{r}
#filter master suicide rate data to 2015 only
sr.2015 <- filter(master_sr, year == "2015")

#join 2015 data
full2015 <- full_join(sr.2015, happy2015, by = c("ï..country" = "Country"))

full2015

sum2015 <- full2015 %>%
  #filter(na.rm == TRUE) %>%
  group_by(Region) %>%
  summarise(suicide_total = sum(suicides_no, na.rm = TRUE), pop = sum(population, na.rm = TRUE), rank = mean(Happiness.Score, na.rm = TRUE))
```


Explore happiness data
```{r}
#top 10 rank
top.ten <- master.happy %>% filter(Happiness.Rank <= 5)
top.ten
  
ggplot(top.ten, aes(x=Happiness.Rank, y=year)) + geom_histogram()
```


Model


Interpret